{% set name = "google-cloud-iam" %}
{% set version = "2.12.2" %}
{% set sha256 = "6031d0c1911fc79ce0b8bb8f6fe1645283b9c1a9188b483dae623b53b4d8181c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.34.0,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - proto-plus >=1.22.0,<2.0.0
    - protobuf >=3.19.5,<5.0.0,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google
    - google.cloud.iam_credentials
    - google.cloud.iam_credentials_v1
    - google.cloud.iam_v2
    - google.api_core
    - grpc
  requires:
    - pip

about:
  summary: IAM Service Account Credentials API client library
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-iam
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "IAM Service Account Credentials API is a Google Cloud service that lets client applications communicate with the Cloud Identity and Access Management (IAM) platform. Cloud IAM lets administrators authorize who can take action on specific resources, giving you full control and visibility to manage Google Cloud
    resources centrally. For enterprises with complex organizational structures, hundreds of workgroups, and many projects, Cloud IAM provides a unified view into security policy across your entire organization, with built-in auditing to ease compliance processes.\nSee the [quick start guide](https://googleapis.dev/python/iamcredentials/latest/index.html#quick-start)."
  doc_url: https://googleapis.dev/python/iamcredentials/latest/index.html
  dev_url: https://github.com/googleapis/python-iam

extra:
  recipe-maintainers:
    - rxm7706
    - parthea
